#!/bin/bash

echo "=================================================="
echo "       Jarvis Assistant Setup Complete!"
echo "=================================================="
echo ""
echo "Next steps:"
echo ""
echo "1. Get your Porcupine access key (free):"
echo "   https://console.picovoice.ai/"
echo ""
echo "2. Edit config.json and add your access key"
echo ""
echo "3. Copy the jarvis.py file to this directory"
echo ""
echo "4. Run the assistant:"
echo "   ./launch_jarvis.sh"
echo ""
echo "Optional: Install as systemd service:"
echo "   sudo cp jarvis.service /etc/systemd/system/jarvis@$USER.service"
echo "   systemctl --user enable jarvis@$USER"
echo "   systemctl --user start jarvis@$USER"
echo ""
echo "=================================================="
echo ""
echo "Directory structure created:"
echo "  ~/.config/jarvis/tasks/    - Task definitions"
echo "  ~/.local/share/jarvis/logs/ - Log files"
echo "  ~/.cache/jarvis/           - Cache files"
echo ""
echo "Models downloaded:"
echo "  models/llama-2-7b-chat.Q4_K_M.gguf - Llama 2 7B"
echo "  ~/.cache/whisper/           - Whisper base model"
echo "  ~/.local/share/piper/voices/ - Piper TTS voice"
echo ""
echo "=================================================="
